name: thanh_portfolio
description: "Portfolio of Thành"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/
